#include "aragorn-trna.h"
#include <vector>
#include <string>

int main(int z, char *v[]) {

/* (642,725,134.442000) */
/* (221,304,134.442000) */

  std::string test_seq = "CGTTTGGGCGACTAGCACCAACCAGATTTAAGCATCGCAAGCTAGTTTTTTTATCTGTGAATAAGAAGGAACATGAAAAGAACAACAGCATTACTACGGCACTCTTATGATTTAAGCCTCAATATGTCCTTTGAATGGTCCAAGCCGTGAATGTCACTGTAAGTAAGTTCAGACTGCATAGTCCCTATTCTGAAGATTGATCAGACATCATCAAGAGCCACGCCCGGTTAGCTCAATCGGTAGAGCGTGAGACTCTTACGAGTACGCGATCTCAAGGTTGCGGGTTCGACCCCCGCATCGGGCTGTTCCTATATTCGATTGCGAGCGTTAGCGAGGCTTTCATTTTTGCATTTTTGTTCTTTGGTACCTTTAAACCTTGCATCTATCTATCTTACGTGCACTGTTCAGTGGATGGAAGAATCGTTTGGGCGACTAGCACCAACCAGATTTAAGCATCGCAAGCTAGTTTTTTTATCTGTGAATAAGAAGGAACATGAAAAGAACAACAGCATTACTACGGCACTCTTATGATTTAAGCCTCAATATGTCCTTTGAATGGTCCAAGCCGTGAATGTCACTGTAAGTAAGTTCAGACTGCATAGTCCCTATTCTGAAGATTGATCAGACATCATCAAGAGCCACGCCCGGTTAGCTCAATCGGTAGAGCGTGAGACTCTTACGAGTACGCGATCTCAAGGTTGCGGGTTCGACCCCCGCATCGGGCTGTTCCTATATTCGATTGCGAGCGTTAGCGAGGCTTTCATTTTTGCATTTTTGTTCTTTGGTACCTTTAAACCTTGCATCTATCTATCTTACGTGCACTGTTCAGTGGATGGAAGAAT";

  std::vector<hit> hits = predict_trnas(test_seq);

  for(size_t i = 0; i < hits.size(); i++){
    fprintf(stdout, "(%ld,%ld,%f)\n", hits[i].start, hits[i].stop, hits[i].energy);
  }

  return(0);
}
