#include "aragorn-trna.h"

int main(int z, char *v[]) {

/* (642,725,134.442000) */
/* (221,304,134.442000) */

  char* test_seq = "CGTTTGGGCGACTAGCACCAACCAGATTTAAGCATCGCAAGCTAGTTTTTTTATCTGTGAATAAGAAGGAACATGAAAAGAACAACAGCATTACTACGGCACTCTTATGATTTAAGCCTCAATATGTCCTTTGAATGGTCCAAGCCGTGAATGTCACTGTAAGTAAGTTCAGACTGCATAGTCCCTATTCTGAAGATTGATCAGACATCATCAAGAGCCACGCCCGGTTAGCTCAATCGGTAGAGCGTGAGACTCTTACGAGTACGCGATCTCAAGGTTGCGGGTTCGACCCCCGCATCGGGCTGTTCCTATATTCGATTGCGAGCGTTAGCGAGGCTTTCATTTTTGCATTTTTGTTCTTTGGTACCTTTAAACCTTGCATCTATCTATCTTACGTGCACTGTTCAGTGGATGGAAGAATCGTTTGGGCGACTAGCACCAACCAGATTTAAGCATCGCAAGCTAGTTTTTTTATCTGTGAATAAGAAGGAACATGAAAAGAACAACAGCATTACTACGGCACTCTTATGATTTAAGCCTCAATATGTCCTTTGAATGGTCCAAGCCGTGAATGTCACTGTAAGTAAGTTCAGACTGCATAGTCCCTATTCTGAAGATTGATCAGACATCATCAAGAGCCACGCCCGGTTAGCTCAATCGGTAGAGCGTGAGACTCTTACGAGTACGCGATCTCAAGGTTGCGGGTTCGACCCCCGCATCGGGCTGTTCCTATATTCGATTGCGAGCGTTAGCGAGGCTTTCATTTTTGCATTTTTGTTCTTTGGTACCTTTAAACCTTGCATCTATCTATCTTACGTGCACTGTTCAGTGGATGGAAGAAT";

  list* gs = predict_trnas(test_seq);

  hit* g;

  while(gs && gs->element){
    g = (hit*) gs->element; 
    fprintf(stdout, "(%ld,%ld,%f)\n", g->start, g->stop, g->energy);
    gs = gs->next;
  }

  return(0);
}
